<?php

/**
 * Implementation of hook_views_api().
 */
function views_infinite_scroll_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'views_infinite_scroll'),
  );
}



/**
 * Implementation of hook_theme(). Register our theming functions.
 */
function views_infinite_scroll_theme() {
  $hooks['views_infinite_scroll_pager'] = array(
    'arguments' => array(
      'tags' => array(), 
      'limit' => 10, 
      'element' => 0, 
      'automatic' => false, 
      'loadingtext' => t('Loading next page...'), 
      'donetext' => t('You\'ve reached the last page'),
      'target' => 'div.view-content',
      'itemselector' => 'div.view-content div.views-row',
     ),
     'pattern' => 'views_infinite_scroll_pager__',
  );
  return $hooks;
}




function theme_views_infinite_scroll_pager($tags = array(), $limit = 10, $element = 0, $automatic = true, $loadingtext = '', $donetext = '', $target = 'div.view-content', $itemselector = 'div.view-content div.views-row') {
  global $pager_page_array, $pager_total;

  drupal_add_js(drupal_get_path('module', 'views_infinite_scroll') . '/jquery.infinitescroll.js');
  $js ="$(document).ready(function(){
    $('" . $target . "').infinitescroll({
      navSelector  : '.infinite-scroll',            
      nextSelector : 'li.pager-next a', 
      loadingImg      : '" . drupal_get_path('module', 'views_infinite_scroll') . "/loading.gif',
      loadingText     : '<em>" . addslashes($loadingtext) . "</em>',
      donetext        : '<em>" . addslashes($donetext) . "</em>',
      debug        : false,  
      itemSelector : '" . $itemselector . "',
    });
  });";
  drupal_add_js($js,'inline');
//  krumo(get_defined_vars());
  

  // current is the page we are currently paged to
  $pager_current = $pager_page_array[$element] + 1;
  // max is the maximum page number
  $pager_max = $pager_total[$element];
  // End of marker calculations.


  $li_previous = theme('pager_previous', (isset($tags[1]) ? $tags[1] : t('‹‹')), $limit, $element, 1, array());
  if (empty($li_previous)) {
    $li_previous = "&nbsp;";
  }

  $li_next = theme('pager_next', (isset($tags[3]) ? $tags[3] : t('››')), $limit, $element, 1, array());
  if (empty($li_next)) {
    $li_next = "&nbsp;";
  }
  if ($pager_total[$element] > 1) {
    $items[] = array(
      'class' => 'pager-previous',
      'data' => $li_previous,
    );

    $items[] = array(
      'class' => 'pager-current',
      'data' => t('@current of @max', array('@current' => $pager_current, '@max' => $pager_max)),
    );

    $items[] = array(
      'class' => 'pager-next',
      'data' => $li_next,
    );
    return '<div class="infinite-scroll">' . theme('item_list', $items, NULL, 'ul', array('class' => 'pager')) . '</div>';
  }

}
