<?php

/**
 * Implementation of hook_views_api().
 */
function views_infinite_scroll_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'views_infinite_scroll'),
  );
}



/**
 * Implementation of hook_theme(). Register our theming functions.
 */
function views_infinite_scroll_theme() {
  $hooks['views_infinite_scroll_pager'] = array(
    'arguments' => array('tags' => array(), 'limit' => 10, 'element' => 0, 'parameters' => array()),
    'pattern' => 'views_infinite_scroll_pager__',
  );
  return $hooks;
}




function theme_views_infinite_scroll_pager($tags = array(), $limit = 10, $element = 0, $parameters = array(), $quantity = 9) {
  global $pager_page_array, $pager_total;

  drupal_add_js(drupal_get_path('module', 'views_infinite_scroll') . '/jquery.infinitescroll.js');
  $js ="$(document).ready(function(){
    $('div.view-content').infinitescroll({
      navSelector  : '.infinite-scroll',            
      nextSelector : 'li.pager-next a', 
      loadingImg      : '" . drupal_get_path('module', 'views_infinite_scroll') . "/loading.gif',
      loadingText     : '<em>Loading next page...</em>',
      donetext        : '<em>You\'ve reached the last page</em>',
      debug        : false,  
      itemSelector : 'div.view-content div.views-row',
    });
  });";
  drupal_add_js($js,'inline');
  
  // Calculate various markers within this pager piece:
  // Middle is used to "center" pages around the current page.
  $pager_middle = ceil($quantity / 2);
  // current is the page we are currently paged to
  $pager_current = $pager_page_array[$element] + 1;
  // max is the maximum page number
  $pager_max = $pager_total[$element];
  // End of marker calculations.


  $li_previous = theme('pager_previous', (isset($tags[1]) ? $tags[1] : t('‹‹')), $limit, $element, 1, $parameters);
  if (empty($li_previous)) {
    $li_previous = "&nbsp;";
  }

  $li_next = theme('pager_next', (isset($tags[3]) ? $tags[3] : t('››')), $limit, $element, 1, $parameters);
  if (empty($li_next)) {
    $li_next = "&nbsp;";
  }
  if ($pager_total[$element] > 1) {
    $items[] = array(
      'class' => 'pager-previous',
      'data' => $li_previous,
    );

    $items[] = array(
      'class' => 'pager-current',
      'data' => t('@current of @max', array('@current' => $pager_current, '@max' => $pager_max)),
    );

    $items[] = array(
      'class' => 'pager-next',
      'data' => $li_next,
    );
    return '<div class="infinite-scroll">' . theme('item_list', $items, NULL, 'ul', array('class' => 'pager')) . '</div>';
  }

}
